name: Playwright Tests

on:
  push:
    branches: [main, master, dev, fix/auth-409]
  pull_request:
    branches: [main, master, dev, fix/auth-409]

jobs:
  test:
    # timeout-minutes: 60
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest]
        license: [FCA, ASIC, CMA, SCB, CYSEC]
        browser: [chromium]
        # browser: [chromium, webkit]
        # browser: [webkit]

    env:
      CI: true
      TEST_BROWSER: ${{ matrix.browser }}
      TEST_LICENSE: ${{ matrix.license }}
      # TEST_LICENSE: FCA
      # TEST_LANG: de,zh
      # TEST_USER: unauthorised,unregistered
      # TEST_CTA: heroBanner
      # TEST_PAGE: markets,forex
      # TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
      # TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - run: npm ci
      - run: npx playwright install --with-deps

      - name: Run tests
        run: npx playwright test

      # - name: Checkout repository
      #   uses: actions/checkout@v4

      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: lts/*

      # - name: Install dependencies
      #   run: npm ci

      # - name: Install Playwright browsers
      #   run: npx playwright install --with-deps

      # - name: Run Playwright tests
      #   run: npx playwright test

      # - name: Upload Allure report
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: allure-report-${{ matrix.license }}-${{ matrix.browser }}
      #     path: allure-report/
