name: Playwright Tests

on:
  push:
    branches: [main, master, dev, "ci/**"]
  pull_request:
    branches: [main, master, dev, "ci/**"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # suite: [markets, footer]
        license: [FCA]
        # license: [FCA, ASIC, CMA, SCB, CySEC]
        user: [authorised]
        # user: [authorised, unauthorised, unregistered]
        browser: [chromium]

    env:
      CI: true
      TEST_BROWSER: ${{ matrix.browser }}
      TEST_LICENSE: ${{ matrix.license }}
      TEST_USER: ${{ matrix.user }}
      # TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
      # TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}

      # TEST_LICENSE: SCB
      # TEST_LANG: de,zh
      # TEST_USER: unauthorised,unregistered
      # TEST_CTA: heroBanner
      # TEST_PAGE: markets,forex

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - run: npm ci
      - run: npx playwright install --with-deps

      - name: Run tests
        run: npm run test:markets

      - name: Generate Allure report
        if: always()
        run: npx allure generate allure-results --clean -o allure-report

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ matrix.license }}-${{ matrix.browser }}
          path: allure-report/

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.license }}
          path: allure-results/
